

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"

Texture2D GBufferB;
Texture2D GBufferD;
Texture2D ReflectionTexture;
Texture2D InputDepth;
Texture2D SceneColor;
Texture2D SceneColorPreAlpha;
Texture2D LumenSpecular;
Texture2D InputVelocity;
RWTexture2D<float> ReactiveMask;
RWTexture2D<float> CompositeMask;
SamplerState Sampler;

float FurthestReflectionCaptureDistance;
float ReactiveMaskReflectionScale;
float ReactiveMaskRoughnessScale;
float ReactiveMaskRoughnessBias;
float ReactiveMaskReflectionLumaBias;
float ReactiveHistoryTranslucencyBias;
float ReactiveHistoryTranslucencyLumaBias;
float ReactiveMaskTranslucencyBias;
float ReactiveMaskTranslucencyLumaBias;
float ReactiveMaskTranslucencyMaxDistance;
float ForceLitReactiveValue;
uint ReactiveShadingModelID;
uint LumenSpecularCurrentFrame;

struct Outputs
{
    float ReactiveMask : SV_TARGET0;
    float CompositeMask : SV_TARGET1;
};

Outputs main(float4 SvPosition : SV_POSITION)
{
    uint2 uPixelCoord = uint2(SvPosition.xy);

    float2 TexelUV = (float2(uPixelCoord)) / (View.ViewSizeAndInvSize.xy + View.ViewRectMin.xy);
    float2 ScreenPos = ViewportUVToScreenPos(TexelUV);
    float4 Output = float4(0.f, 0.f, 0.f, 0.f);
    float4 BufferB = GBufferB[uPixelCoord];
    float4 BufferD = GBufferD[uPixelCoord];
    float4 FullSceneColor = saturate(SceneColor[uPixelCoord]);
    float4 SceneColorNoAlpha = saturate(SceneColorPreAlpha[uPixelCoord]);
    float CurrentDepth = InputDepth[uPixelCoord].x;

    TexelUV = (float2(uPixelCoord.xy)) / (View.BufferSizeAndInvSize.xy + View.ViewRectMin.xy);
    float4 Reflection = ReflectionTexture.SampleLevel(Sampler, TexelUV, 0);

    if (LumenSpecularCurrentFrame == 0)
    {
        float4 EncodedVelocity = InputVelocity[uPixelCoord];
            {
            float3 PosWithDepth = float3(ScreenPos.xy, CurrentDepth);
            float4 CurrentClipPos = float4(PosWithDepth.xy, PosWithDepth.z, 1);
            float4 PrevClipPos = mul(CurrentClipPos, View.ClipToPrevClip);
            float2 PrevScreenPos = PrevClipPos.xy / PrevClipPos.w;
            float2 PosOffset = PosWithDepth.xy - PrevScreenPos;
            bool bHasVelocity = EncodedVelocity.x > 0.0;
            if (bHasVelocity)
            {
                PosOffset = DecodeVelocityFromTexture(EncodedVelocity).xy;
            }
            TexelUV = ScreenPosToViewportUV(ScreenPos.xy - PosOffset);
        }
    }
    float4 Specular = LumenSpecular.SampleLevel(Sampler, TexelUV, 0);

    float2 TranslucencyContribution = float2(0.f, 0.f);

    FGBufferData GBuffer = DecodeGBufferData(float4(0.f, 0.f, 0.f, 0.f),
                                                    BufferB,
                                                    float4(0.f, 0.f, 0.f, 0.f),
                                                    BufferD,
                                                    float4(0.f, 0.f, 0.f, 0.f),
                                                    float4(0.f, 0.f, 0.f, 0.f),
                                                    float4(0.f, 0.f, 0.f, 0.f),
                                                    0.f,
                                                    0,
                                                    0.f,
                                                    false,
                                                    false);

    float Roughness = GBuffer.Roughness;
    float ForceReactive = 0.f;
    if (GBuffer.ShadingModelID == SHADINGMODELID_CLEAR_COAT)
    {
        const float ClearCoat = GBuffer.CustomData.x;
        const float ClearCoatRoughness = GBuffer.CustomData.y;

        Roughness = lerp(Roughness, ClearCoatRoughness, ClearCoat);
    }
    else if (GBuffer.ShadingModelID == SHADINGMODELID_UNLIT)
    {
        Roughness = 1.0f;
    }

    if (GBuffer.ShadingModelID == ReactiveShadingModelID)
    {
        ForceReactive = ForceLitReactiveValue > 0.f ? ForceLitReactiveValue : GBuffer.CustomData.x;
    }

    float3 Delta = abs(FullSceneColor - SceneColorNoAlpha).xyz;

    float PreDOFTranslucency = 0.f;
    float4 Translucency = float4(Delta, 1.f - Luminance(Delta));

    float WorldDepth = ConvertFromDeviceZ(CurrentDepth);
    float4 NewSvPosition = float4(SvPosition.xy, CurrentDepth, WorldDepth);
    float3 TranslatedWorldPosition = SvPositionToTranslatedWorld(NewSvPosition);
    float NormalizedDistanceToCapture = saturate(length(TranslatedWorldPosition) / FurthestReflectionCaptureDistance);
    Roughness = (FurthestReflectionCaptureDistance > 0.f) ? lerp(Roughness, 1.f, NormalizedDistanceToCapture) : Roughness;

    TranslucencyContribution.x = ((1.f - Translucency.w) * ReactiveMaskTranslucencyBias) + (ReactiveMaskTranslucencyLumaBias * saturate(Luminance(Translucency.xyz)) * Translucency.w);
    TranslucencyContribution.y = ((1.f - Translucency.w) * ReactiveHistoryTranslucencyBias) + (ReactiveHistoryTranslucencyLumaBias * saturate(Luminance(Translucency.xyz)) * Translucency.w);

    float NormalizedDistanceToSurface = saturate(length(TranslatedWorldPosition) / ReactiveMaskTranslucencyMaxDistance);
    TranslucencyContribution = (ReactiveMaskTranslucencyMaxDistance > 0.f) ? lerp(TranslucencyContribution, 0.f, float2(NormalizedDistanceToSurface, NormalizedDistanceToSurface)) : TranslucencyContribution;

    Output.z = saturate((1.f - Roughness) * ReactiveMaskRoughnessScale);

    float ReflectionContribution = 0.f;
    if (Reflection.w > 0.f && ReactiveMaskReflectionScale > 0.f)
    {
        Output.w = Luminance(Reflection.xyz) * ReactiveMaskReflectionLumaBias;
        ReflectionContribution = lerp((Reflection.w * ReactiveMaskReflectionScale), 1.f, Output.w);
        ReflectionContribution += (max(Output.z - ReflectionContribution, 0.f) * ReactiveMaskRoughnessBias);
    }
    else if (any(Specular.xyz) && ReactiveMaskReflectionScale > 0.f)
    {
        ReflectionContribution = saturate(Luminance(Specular.xyz)) * ReactiveMaskReflectionScale * (1.f - Roughness);
        ReflectionContribution += (max(Output.z - ReflectionContribution, 0.f) * ReactiveMaskRoughnessBias);
    }
    else
    {
        ReflectionContribution = Output.z;
    }

    Output.x = saturate(TranslucencyContribution.x + ReflectionContribution);
    Output.y = lerp(0.f, 1.f, TranslucencyContribution.y);

    Outputs res;
    res.CompositeMask = Output.x;
    res.ReactiveMask = max(ForceReactive, Output.y);

    return res;
}
